export interface WordEntry {
  word: string;
  hints: [string, string];
}

export const WORDS: WordEntry[] = [
  { word: "FALDA", hints: ["Prenda de vestir que cae desde la cintura", "Puede ser mini, midi o larga"] },
  { word: "BOLSO", hints: ["Accesorio para llevar tus cosas", "Los hay de mano, de hombro o mochila"] },
  { word: "TACON", hints: ["Parte del zapato que te hace más alta", "Elegante para fiestas y eventos"] },
  { word: "BLUSA", hints: ["Prenda superior femenina", "Sueña ser de tela ligera y elegante"] },
  { word: "BOTAS", hints: ["Calzado que cubre el pie y parte de la pierna", "Ideales para el invierno o la lluvia"] },
  { word: "GAFAS", hints: ["Accesorio para proteger los ojos del sol", "También llamadas lentes o anteojos"] },
  { word: "PERLA", hints: ["Gema blanca que viene de las ostras", "Clásica, elegante y atemporal"] },
  { word: "ARETE", hints: ["Joya que se cuelga en las orejas", "También llamado pendiente o zarcillo"] },
  { word: "LAZOS", hints: ["Adornos hechos con cintas", "Se usan mucho en el pelo o en la ropa"] },
  { word: "MALLA", hints: ["Prenda ajustada para hacer deporte", "Muy cómoda, elástica y versátil"] },
  { word: "BATAS", hints: ["Prenda cómoda para estar por casa", "Se pone encima del pijama al despertar"] },
  { word: "MONOS", hints: ["Prenda de una sola pieza", "Pantalón y cuerpo unidos en uno"] },
  { word: "GORRA", hints: ["Accesorio para la cabeza con visera", "Protege del sol con un toque deportivo"] },
  { word: "SEDAS", hints: ["Tejido muy suave y brillante", "De origen natural y tacto lujoso"] },
  { word: "JOYAS", hints: ["Objetos de valor para adornarse", "Hechos de oro, plata o piedras preciosas"] },
  { word: "GEMAS", hints: ["Piedras preciosas o semipreciosas", "Brillan mucho cuando les da la luz"] },
  { word: "RUBIS", hints: ["Piedras preciosas de color rojo intenso", "Muy valiosas y símbolo de pasión"] },
  { word: "RIZOS", hints: ["Forma ondulada o espiral del cabello", "Se pueden definir con espuma o gel"] },
  { word: "PEINE", hints: ["Utensilio para desenredar el cabello", "Tiene púas finas y mango largo"] },
  { word: "RUBOR", hints: ["Maquillaje para dar color a las mejillas", "También conocido como colorete"] },
  { word: "RIMEL", hints: ["Maquillaje para las pestañas", "Las hace ver más largas y voluminosas"] },
  { word: "POLVO", hints: ["Maquillaje para matizar el rostro", "Evita los brillos y sella la base"] },
  { word: "GLOSS", hints: ["Brillo labial transparente o con color", "Deja los labios jugosos y brillantes"] },
  { word: "AROMA", hints: ["Olor agradable de un buen perfume", "Te hace dejar huella por donde pasas"] },
  { word: "CORTE", hints: ["Estilo de peinado o forma de la ropa", "Puede ser bob, pixie o a capas"] },
  { word: "TALLA", hints: ["Medida de la ropa o el calzado", "S, M, L o números específicos"] },
  { word: "LINDA", hints: ["Adjetivo para alguien muy agraciada", "Sinónimo de bonita o bella"] },
  { word: "BELLA", hints: ["Alguien con una belleza excepcional", "Como la protagonista de un cuento"] },
  { word: "GUAPA", hints: ["Alguien atractiva físicamente", "Un piropo muy común en España"] },
  { word: "REINA", hints: ["Mujer que lleva una corona", "La figura más importante de la corte"] },
  { word: "DIVAS", hints: ["Mujeres con mucha personalidad y talento", "Grandes estrellas del cine o la música"] },
  { word: "MUSAS", hints: ["Mujeres que inspiran a los artistas", "Diosas que despiertan la creatividad"] },
  { word: "HADAS", hints: ["Seres mágicos diminutos con alas", "Viven en el bosque y conceden deseos"] },
  { word: "ROSAS", hints: ["Flores románticas por excelencia", "Tienen pétalos suaves y tallos con espinas"] },
  { word: "LIRIO", hints: ["Flor elegante de pétalos grandes", "Símbolo de pureza y majestuosidad"] },
  { word: "CREMA", hints: ["Producto para hidratar y cuidar la piel", "Se aplica con un suave masaje"] },
  { word: "LABIO", hints: ["Parte de la boca donde se aplica el carmín", "Esencial para sonreír y besar"] },
  { word: "MODAS", hints: ["Tendencias de ropa de cada temporada", "Lo que dictan las pasarelas de París"] },
  { word: "TRAJE", hints: ["Conjunto de chaqueta y falda o pantalón", "Look profesional para ir a la oficina"] },
  { word: "VELOS", hints: ["Telas finas que cubren la cara o el pelo", "Accesorio clásico para las novias"] },
  { word: "MONOS", hints: ["Peinado recogido en forma de bola", "Elegante, despejado y muy chic"] },
  { word: "TINTA", hints: ["Producto para cambiar el color del pelo", "Sirve para dar reflejos o cubrir canas"] },
  { word: "DIEMA", hints: ["Accesorio para sujetar el pelo", "Se coloca sobre la cabeza como un arco"] },
  { word: "MANOS", hints: ["Parte del cuerpo que luce la manicura", "Donde se ponen las pulseras y anillos"] },
  { word: "TOPES", hints: ["Prendas superiores muy cortas", "Ideales para combinar con faldas altas"] },
  { word: "CHICA", hints: ["Mujer joven o niña", "La protagonista de este juego"] }
];

export const getRandomWordEntry = () => WORDS[Math.floor(Math.random() * WORDS.length)];
